language: python

python:
  - "2.7"

install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  # Syntax check every ansible playbook in root
  # Don't check main, though, as vars_prompt still
  # trigger during syntax checks, and travis fails
  #- find . -maxdepth 1 -type f -name '*.yml' -not -name '.*' -not -name 'main.yml' | xargs -t -n1 ansible-playbook --syntax-check -i hosts_vagrant
  # - echo password > vault_pass.txt
  - cp vars/secret.yml.example vars/secret.yml
  # - ansible-vault encrypt --vault-password-file=./vault_pass.txt vars/secret.yml
  - ansible-playbook -i test/inventory --syntax-check --list-tasks test/test.yml
  - ansible-playbook -i test/inventory --connection=local --sudo -vvvv test/test.yml
