---
- hosts: common
  roles:
  - { role: common, when: ansible_os_family == 'Debian' }
  sudo: yes
  vars_files:
    - vars/secret.yml
  # accelerate: true
  # remote_user: root
  # tasks:
  # - debug: msg="{{ inventory_dir }}"
  # - debug: msg="{{ lookup('file', users[0].ssh_keys) }} is an environment variable"

  # - name: SSH keys
  #   authorized_key:
  #     user={{ item.0.name }}
  #     key="{{ lookup('file', item.1) }}"
  #   with_subelements:
  #      - users
  #      - ssh_keys
    # - authorized_key: user="{{ item.0.name }}"
    #     key="{{ lookup('file', item.1) }}"
    #   with_subelements:
    #    - users
    #    - ssh_keys