---
- name: restart ssh
  service: name=ssh state=reloaded

- name: restart iptables
  shell: /etc/network/if-up.d/iptables

- name: update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: run locale-gen
  command: locale-gen

- name: restart ntp
  service: name=ntp state=restarted

- name: restart exim4
  service: name=exim4 state=restarted
- name: update exim4 conf
  shell: update-exim4.conf
