- name: Install exim
  apt:
    pkg: exim4
    state: latest
  tags: [configuration, exim]

- name: Set /etc/exim4/update-exim4.conf.conf
  template: dest=/etc/exim4/update-exim4.conf.conf src=update-exim4.conf.conf.j2
  notify:
    - update exim4 conf
    - restart exim4
  tags: [configuration, exim]

- name: Set /etc/exim4/passwd.client
  template: dest=/etc/exim4/passwd.client src=passwd.client.j2
  notify:
    - update exim4 conf
    - restart exim4
  tags: [configuration, exim]


- name: Set email for user root
  replace: "dest=/etc/aliases regexp='^root.*$' replace='root: {{ root_mail }}'"
  tags: [configuration, exim]
