---
- include: packages.yml
- include: hostname.yml
- include: locale.yml
- include: timezone.yml
- include: ntp.yml
- include: users.yml
- include: ssh.yml
- include: iptables.yml
- include: exim.yml