---
- name: ntp | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - ntp
    - ntpdate
  tags: [configuration, ntp]


- name: Ensure NTP is running and enabled at system start
  service: >
    name=ntp
    state=started
    enabled=yes
  tags: [configuration, ntp]
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled at system start
  service: >
    name=ntp
    state=stopped
    enabled=no
  tags: [configuration, ntp]
  when: not ntp_enabled
