---
# tasks file for timezone
- name: Set the correct timezone.
  file: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
        state=link
        force=yes
        backup=yes
  when: ansible_os_family == "Debian"
  tags: [configuration,timezone]

- name: "Set /etc/timezone to {{ timezone }}"
  template: dest=/etc/timezone src=timezone.j2
  notify: update tzdata
  when: ansible_os_family == "Debian"
  tags: [configuration,timezone]